var Data=
[
  {
    id:1,
    name: "URU BrewPark",
    votes:766,
    reviews:233,
    Min:50,
    Cost_for_two:300,
    ratings:4.2,
    categories:"Continental",
    Payment_method:
    {
      card:true,
      cash:false,
      upi:false,
    }
  },
  {
    id:2,
    name: "URU BrewPark",
    votes:766,
    reviews:233,
    Min:50,
    Cost_for_two:150,
    ratings:3.2,
    categories:"Continental",
    Payment_method:
    {
      card:true,
      cash:false,
      upi:true,
    }
  },
  {
    id:3,
    name: "URU BrewPark",
    votes:766,
    reviews:233,
    Min:50,
    Cost_for_two:520,
    ratings:2.6,
    categories:"Continental",
    Payment_method:
    {
      card:false,
      cash:true,
      upi:false,
    }
  },
  {
    id:4,
    name: "URU BrewPark",
    votes:766,
    reviews:233,
    Min:50,
    Cost_for_two:660,
    ratings:4.1,
    categories:"Continental",
    Payment_method:
    {
      card:false,
      cash:true,
      upi:true,
    }
  },
  {
    id:5,
    name: "URU BrewPark",
    votes:766,
    reviews:233,
    Min:50,
    Cost_for_two:470,
    ratings:3,
    categories:"Continental",
    Payment_method:
    {
      card:true,
      cash:true,
      upi:false,
    }
  },
  {
    id:6,
    name: "URU BrewPark",
    votes:766,
    reviews:233,
    Min:50,
    Cost_for_two:230,
    ratings:3.9,
    categories:"Continental",
    Payment_method:
    {
      card:true,
      cash:false,
      upi:true,
    }
  },
  {
    id:7,
    name: "URU BrewPark",
    votes:766,
    reviews:233,
    Min:50,
    Cost_for_two:870,
    ratings:1.2,
    categories:"Continental",
    Payment_method:
    {
      card:true,
      cash:false,
      upi:false,
    }
  },
  {
    id:8,
    name: "URU BrewPark",
    votes:766,
    reviews:233,
    Min:50,
    Cost_for_two:1100,
    ratings:4.1,
    categories:"Continental",
    Payment_method:
    {
      card:false,
      cash:true,
      upi:true,
    }
  },
  {
    id:9,
    name: "URU BrewPark",
    votes:766,
    reviews:233,
    Min:50,
    Cost_for_two:456,
    ratings:4,
    categories:"Continental",
    Payment_method:
    {
      card:true,
      cash:false,
      upi:false,
    }
  },
  {
    id:10,
    name: "URU BrewPark",
    votes:766,
    reviews:233,
    Min:50,
    Cost_for_two:910,
    ratings:2.9,
    categories:"Continental",
    Payment_method:
    {
      card:false,
      cash:true,
      upi:false,
    }
  }
]

export {Data}